---
title: "Likelihood Stuff"
author: "Dan Ovando"
output:
  word_document: default
  html_document:
    fig_align: center
    fig_caption: yes
    fig_height: 6
    fig_width: 8
---
```{r global_options, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(fig.path='Figs/', echo=FALSE, warning=FALSE, message=FALSE)

library(gridExtra)
library(ggplot2)
library(plyr)
library(dplyr)
library(tidyr)
library(knitr)
```

The Namibian hake example from *The Ecological Detective*. 

```{r load in data}

devtools::load_all('~/R Functions/mletools')

devtools::load_all('~/R Functions/PopulationModels')

hakedata <- read.csv('namibian_hake_data.csv', stringsAsFactors = F)

kable(summary(hakedata), caption = 'Summary of Namibian hake data')

hake_plot <- (ggplot(gather(hakedata,'Data','Value',2:3),aes(year,Value, fill = Data)) + geom_point(shape = 21) + facet_grid(Data~., scales = 'free_y') +scale_fill_discrete(guide = FALSE))

hake_plot

r_guess <- 0.1

k_guess <- 10*max(hakedata$catch)

q_guess <- .001

sdev_guess <- sd(hakedata$cpue)

schaefer_hake_fit <- nlminb(start = c(r_guess,k_guess,q_guess,sdev_guess), objective = schaefer_mle,dat = hakedata,
                            use = 'optimization', pars_to_opt = c('r','k','q','sdev'), lower = c(0.01,.01,1e-7,1e-7),
                            upper = c(1,Inf,1,Inf))


schaefer_fit <- schaefer_mle(params =schaefer_hake_fit$par, dat = hakedata)

```

```{r, fig.cap= 'MLE fit of schaefer model with observation error'}
sch_cpue_fit <- (ggplot(schaefer_fit$dat,aes(year,cpue, shape = 'Observed')) + 
                   geom_point() + 
                   geom_line(aes(year,predicted_cpue,linetype = 'Predicted'), color = 'red') + theme(legend.title = element_blank()))

sch_cpue_fit

```

```{r plot fits}
# 
# schaefer_summary <- data.frame(msy_est= mean(schaefer_fit$MSY),r_est = mean(schaefer_fit$r),k_est =mean(schaefer_fit$k), q_est = mean(schaefer_fit$q), sdev_est = mean(schaefer_fit$sdev))

kable((schaefer_fit$model_summary), caption = 'summary of MLE estimates of schaefer parameters with observation error')

```

Now, explore likelihood profile of the various things

```{r}

likelihood_plots <- schaefer_profile(r_range = seq(.2,.7,by = 0.05), k_range = seq(2000,4000, by = 100),msy_range = seq(200,400,by = 25), dat = hakedata)

likelihood_plots

# schaefer_hake_fit <- nlminb(start = c(r_guess,k_guess), objective = schaefer_mle,dat = hakedata,
#        use = 'optimization', pars_to_opt = c('r','k'), lower = c(0.01,.01),
#        upper = c(1,Inf), fixed_q = .0008,fixed_sdev = .08)

```

# Schaefer with Process Uncertainty

```{r now do process uncertainty, fig.cap = 'fit of schaefer with process error'}

r_guess <- 0.3

k_guess <- 6000

q_guess <- .0005

sdev_guess <- .1

schaefer_hake_fit <- nlminb(start = c(r_guess,k_guess,q_guess,sdev_guess), objective = schaefer_mle,dat = hakedata,
                            use = 'optimization', pars_to_opt = c('r','k','q','sdev'), lower = c(0.01,0.01,1e-7,1e-7),
                            upper = c(1,Inf,1,Inf),error_type = 'process')


schaefer_fit <- schaefer_mle(params =schaefer_hake_fit$par, dat = hakedata,error_type = 'process')

# schaefer_fit <- schaefer_mle(params =c(.32,3519,.00026,.1), dat = hakedata,error_type = 'process')$model_summary

sch_cpue_fit <- (ggplot(schaefer_fit$dat,aes(year,cpue)) + 
                   geom_point() + 
                   geom_line(aes(year,predicted_cpue), color = 'red'))

sch_cpue_fit
# 
# schaefer_summary <- data.frame(msy_est= mean(schaefer_fit$MSY),r_est = mean(schaefer_fit$r),k_est =mean(schaefer_fit$k), q_est = mean(schaefer_fit$q), sdev_est = mean(schaefer_fit$sdev))

kable((schaefer_fit$model_summary), caption = 'summary of MLE estimates of schaefer parameters with process error')

```

```{r process error schaefer likelihood profiles}

likelihood_plots <- schaefer_profile(r_range = seq(.2,.4,by = 0.01), k_range = seq(2000,4000, by = 50),msy_range = seq(200,400,by = 25), dat = hakedata, error_type = 'process', r_guess = r_guess, k_guess = k_guess,q_guess = q_guess,analytic_q = F)

likelihood_plots

```

# LRSG Model

```{r, LRSG mle fit}

b0_guess <- 3000

s_guess <- 0.9

z_guess <- 0.9

q_guess <- .0004

sdev_guess <- 0.12

lrsg_fit <- nlminb(start =c(b0_guess,s_guess,z_guess,sdev_guess,q_guess),objective = lrsg_mle,pars_to_opt = c('b0','s','z','sdev','q'), dat = hakedata,use = 'optimization',
                   lower = c(.01,.01,.01,.01,1e-7), upper = c(Inf,1,.99,Inf,1))

lrsg_run <- lrsg_mle(params = lrsg_fit$par,dat = hakedata,pars_to_opt = c('b0','s','z','sdev','q'),use = 'simulation')

cpue_plot <- (ggplot(lrsg_run$dat, aes(year,cpue)) +
                geom_point(shape = 21, fill = 'blue') +
                geom_line(aes(year,predicted_cpue)) +
                xlab('year') +
                ylab('cpue'))

kable(lrsg_run$model_summary, caption = 'Summary of LRSG MLE fit')

```

```{r, Bayes MCMC}

b0_range <- c(1000,5000)

s_range <- c(.65,.99)

z_range <- c(0.8,.99)

lrsg_monte_carlo <- lapply(1:10000,lrsg_bayes,b0_range = b0_range,s_range = s_range,z_range = z_range, dat = hakedata) %>% ldply()

par(mfrow = c(2,2))
plot(lrsg_monte_carlo$b0,lrsg_monte_carlo$likelihood)
plot(lrsg_monte_carlo$s,lrsg_monte_carlo$likelihood)
plot(lrsg_monte_carlo$z,lrsg_monte_carlo$likelihood)
plot(lrsg_monte_carlo$MSY,lrsg_monte_carlo$likelihood)




```
